module.exports = {
  'digital-transformation': 'Why Digital Transformation Fails in Most Organisations',
  'customer-retention': 'The Hidden Economics of Customer Retention',
  'pricing-strategy': 'Strategic Pricing in Uncertain Markets',
  'market-segmentation': 'Beyond Demographics: Modern Market Segmentation',
  'revenue-growth': 'Unlocking Organic Revenue Growth',
  'innovation-culture': 'Building Innovation Capabilities at Scale',
  'data-analytics': 'Turning Data into Competitive Advantage',
  'customer-journey': 'Mapping the Modern B2B Buyer Journey',
  'brand-positioning': 'Differentiation Strategies that Actually Work',
  'sales-productivity': 'Scaling Sales Without Scaling Headcount',
  'marketing-roi': 'Measuring What Matters in Marketing Performance',
  'channel-strategy': 'Optimising Multi-Channel Distribution',
  'competitive-advantage': 'Sustainable Competitive Advantage in Digital Age',
  'organizational-change': 'Leading Transformation in Traditional Industries',
  'product-innovation': 'From Product Features to Customer Outcomes',
  'market-expansion': 'International Growth Strategies for Mid-Market Firms',
  'operational-excellence': 'Process Innovation for Margin Improvement',
  'talent-strategy': 'Winning the War for Strategic Talent',
  'ecosystem-partnerships': 'Platform Business Models and Ecosystem Strategy',
  'sustainability-strategy': 'Embedding Sustainability into Core Operations',
  'tech-adoption': 'Technology Investment Decisions That Create Value',
  'customer-experience': 'Engineering Exceptional Customer Experiences',
  'market-disruption': 'Responding to Industry Disruption',
  'growth-strategy': 'Portfolio Strategy for Diversified Growth',
  'value-proposition': 'Crafting Value Propositions That Resonate'
};